// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {scanner} from '../models';

export function GetAvaliableServices():Promise<Array<string>>;

export function GetDiskStats(arg1:string):Promise<storage.DiskStats>;

export function Greet(arg1:string):Promise<string>;

export function SearchFiles(arg1:string,arg2:Array<string>,arg3:string,arg4:boolean):Promise<Array<scanner.Result>>;
