// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSearch(arg1) {
  return window['go']['main']['App']['CancelSearch'](arg1);
}

export function GetAvaliableServices() {
  return window['go']['main']['App']['GetAvaliableServices']();
}

export function GetDiskStats(arg1) {
  return window['go']['main']['App']['GetDiskStats'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SearchFiles(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2, arg3, arg4, arg5, arg6);
}
