// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {scanner} from '../models';

export function CancelSearch(arg1:string):Promise<void>;

export function GetAvaliableServices():Promise<Array<string>>;

export function GetDiskStats(arg1:string):Promise<storage.DiskStats>;

export function OpenInFolder(arg1:string,arg2:boolean):Promise<void>;

export function OpenWithDefaultEditor(arg1:string,arg2:boolean):Promise<void>;

export function SearchFiles(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:number,arg6:string):Promise<scanner.SearchStats>;
